version: "3"

services:

  postgres:
    image: postgres:11.5
    volumes:
      - pp:/var/lib/postgresql/data:z
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: .env

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "postgres"
    command: "postgres:${POSTGRES_PORT}"

  web:
    build: .
    restart: always
    command: "bash -c ${SERVE_COMMAND}"
    volumes:
      - ./app:/vol/app:z
      - ppstatic:/vol/static_files:z
    expose:
      - 8000
    links:
      - "postgres:postgres"
    env_file: .env
    depends_on:
      - start_dependencies

  nginx:
    image: nginx:1.17.4
    restart: always
    volumes:
      - ppstatic:/vol/static_files:z
      - ${REAL_IMAGE_DIR}:/vol/img:z
      - ${VUE_DIST}:/vol/vue:z
      - ./nginx:/etc/nginx/conf.d:z
    ports:
      - "${NGINX_PORT}:4000"
      - "443:443"
    env_file: .env
    links:
      - "web:web"
    depends_on:
      - start_dependencies
      - web
    command: sh -c "envsubst '$$ALLOWED_HOSTS $$CERT_PATH $$KEY_PATH' < /etc/nginx/conf.d/pp.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  pp:
  ppstatic:
