version: "3"

services:

  postgres:
    image: postgres:12
    volumes:
      - pp:/var/lib/postgresql/data:z
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: .env

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "postgres"
    command: "postgres:${POSTGRES_PORT}"

  web:
    build: .
    restart: always
    command: "bash -c ${SERVE_COMMAND}"
    volumes:
      - ./app:/vol/app:z
      - ppstatic:/vol/static_files:z
      - ${REAL_IMAGE_DIR}:/vol/img:z
    expose:
      - 8000
    links:
      - "postgres:postgres"
    env_file: .env
    depends_on:
      - start_dependencies

  nginx:
    image: nginx:1.17.4
    restart: always
    volumes:
      - ppstatic:/vol/static_files:z
      - ${REAL_IMAGE_DIR}:/vol/img:z
      - ${VUE_DIST}:/vol/vue:z
      - ./nginx:/etc/nginx/conf.d:z
    ports:
      - "${NGINX_PORT}:4000"
      - "80:80"
    env_file: .env
    links:
      - "web:web"
      - "iiif:iiif"
    depends_on:
      - start_dependencies
      - web
    command: sh -c "envsubst '$$ALLOWED_HOSTS $$CERT_PATH $$KEY_PATH $$PP_NGINX_LISTEN $$PP_NGINX_SERVER_NAME' < /etc/nginx/conf.d/pp.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  iiif:
    image: mdlincoln/go-iiif-vips:latest
    restart: always
    volumes:
      - ./iiif:/etc/iiif-server:z
      - ${REAL_IMAGE_DIR}:/usr/local/images:z
    expose:
      - 80
    command: "/bin/iiif-server -host 0.0.0.0 -port 80 -config-source file:///etc/iiif-server -config-name config.json"


volumes:
  pp:
  ppstatic:
